//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;
namespace Final_Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class accfuctional
    {
        public int AccF_ID { get; set; }
        public int AccF_MsID { get; set; }
        public string AccF_FName { get; set; }
        public string AccF_LName { get; set; }
        public Nullable<System.DateTime> AccF_DOB { get; set; }

        [DataType(DataType.PhoneNumber)]
        [RegularExpression(@"^\(?([0-9]{5})\)?[-. ]?([0-9]{7})?[-. ]?([0-9]{1})$", ErrorMessage = "Not a valid CNIC number")]
        public string AccF_CNIC { get; set; }
        [DataType(DataType.PhoneNumber)]
        [RegularExpression(@"^\(?([0-9]{4})\)?[-. ]?([0-9]{7})$", ErrorMessage = "Not a valid phone number")]
        public string AccF_Phone { get; set; }
        public string AccF_Address { get; set; }
        public byte[] AccF_Pic { get; set; }

        [DataType(DataType.EmailAddress)]
        [EmailAddress]
        public string AccF_Email { get; set; }
        public Nullable<bool> AccF_Gender { get; set; }
        public string AccF_PasswordName { get; set; }
        public string AccF_Qualification { get; set; }
        public string AccF_userNumber { get; set; }
        public string AccF_password { get; set; }
    
        public virtual m m { get; set; }
    }
}
