//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Final_Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class attendancep
    {
        public attendancep()
        {
            this.attendances = new HashSet<attendance>();
        }
    
        public int Att_ID { get; set; }
        public int T_ID { get; set; }
        public int S_IID { get; set; }
        public int C_IID { get; set; }
        public Nullable<System.DateTime> Att_date { get; set; }
    
        public virtual tchrfunctional tchrfunctional { get; set; }
        public virtual subject subject { get; set; }
        public virtual @class @class { get; set; }
        public virtual ICollection<attendance> attendances { get; set; }
    }
}
