//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Final_Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class attendance
    {
        public int Att_Pkey { get; set; }
        public int A_ID { get; set; }
        public string Studnt_ID { get; set; }
        public string Studnt_NAME { get; set; }
        public bool A_status { get; set; }
    
        public virtual attendancep attendancep { get; set; }
    }
}
