//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Final_Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class @class
    {
        public @class()
        {
            this.subjects = new HashSet<subject>();
        }
    
        public int Class_ID { get; set; }
        public Nullable<double> Class_Fee { get; set; }
        public string Class_Name { get; set; }
        public int MS_id { get; set; }
    
        public virtual m m { get; set; }
        public virtual ICollection<subject> subjects { get; set; }
    }
}
