//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Final_Project.Models
{
    using System;
    using System.Collections.Generic;

    using System.ComponentModel.DataAnnotations;

    public partial class m
    {
        public m()
        {
            this.accfuctionals = new HashSet<accfuctional>();
            this.classes = new HashSet<@class>();
            this.hrfuctionals = new HashSet<hrfuctional>();
            this.roledatas = new HashSet<roledata>();
            this.studfuctionals = new HashSet<studfuctional>();
        }
    
        public int MS_ID { get; set; }
        public long C_ID { get; set; }
        public string MS_InstName { get; set; }
        public string MS_InstAddress { get; set; }

        [Required(ErrorMessage = "Incorrent Phone Number")]
        [RegularExpression(@"^\(?([0-9]{4})\)?[-. ]?([0-9]{7})$", ErrorMessage = "Not a valid phone number")]
        public string MS_InstPhone { get; set; }
        
        public byte[] MS_logo { get; set; }

        public string MS_InstBranch { get; set; }
    
        public virtual ICollection<accfuctional> accfuctionals { get; set; }
        public virtual ICollection<@class> classes { get; set; }
        public virtual creator creator { get; set; }
        public virtual ICollection<hrfuctional> hrfuctionals { get; set; }
        public virtual ICollection<roledata> roledatas { get; set; }
        public virtual ICollection<studfuctional> studfuctionals { get; set; }
    }
}
