//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Final_Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class marksp
    {
        public marksp()
        {
            this.marksses = new HashSet<markss>();
            this.markstotals = new HashSet<markstotal>();
        }
    
        public int Marks_ID { get; set; }
        public int Mtchr_ID { get; set; }
        public int Msubj_ID { get; set; }
        public int Mclas_ID { get; set; }
        public string Mname { get; set; }
        public Nullable<System.DateTime> Mdate { get; set; }
    
        public virtual @class @class { get; set; }
        public virtual tchrfunctional tchrfunctional { get; set; }
        public virtual subject subject { get; set; }
        public virtual ICollection<markss> marksses { get; set; }
        public virtual ICollection<markstotal> markstotals { get; set; }
    }
}
