//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Final_Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class notification
    {
        public int Noti_ID { get; set; }
        public Nullable<int> Sender_ID { get; set; }
        public Nullable<int> Reciever_ID { get; set; }
        public string Message { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<System.TimeSpan> Time { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string type { get; set; }
    }
}
