//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Final_Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class roledata
    {
        public roledata()
        {
            this.role_funcdata = new HashSet<role_funcdata>();
        }
    
        public int Role_ID { get; set; }
        public string Role_Name { get; set; }
        public Nullable<bool> Role_Portal { get; set; }
        public Nullable<bool> Role_Fname { get; set; }
        public Nullable<bool> Role_Lname { get; set; }
        public Nullable<bool> Role_Dob { get; set; }
        public Nullable<bool> Role_Gender { get; set; }
        public Nullable<bool> Role_Pic { get; set; }
        public Nullable<bool> Role_Qualif { get; set; }
        public Nullable<bool> Role_Email { get; set; }
        public Nullable<bool> Role_CNIC { get; set; }
        public Nullable<bool> Role_FmailyID { get; set; }
        public Nullable<bool> Role_Phone { get; set; }
        public Nullable<bool> Role_Address { get; set; }
        public Nullable<bool> Role_pay { get; set; }
        public Nullable<bool> Role_FthrName { get; set; }
        public Nullable<bool> Role_FthrCNIC { get; set; }
        public Nullable<bool> Role_FthrPhone { get; set; }
        public Nullable<bool> Role_PendingFee { get; set; }
        public int MS_iid { get; set; }
    
        public virtual m m { get; set; }
        public virtual ICollection<role_funcdata> role_funcdata { get; set; }
    }
}
