//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Final_Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class role_funcdata
    {
        public int fun_id { get; set; }
        public int Role_ID { get; set; }
        public Nullable<bool> ViewNotification { get; set; }
        public Nullable<bool> ViewChallan { get; set; }
        public Nullable<bool> GiveNotification { get; set; }
        public Nullable<bool> AddStudent { get; set; }
        public Nullable<bool> DeleteStudent { get; set; }
        public Nullable<bool> UpdateStudent { get; set; }
        public Nullable<bool> updateHR { get; set; }
        public Nullable<bool> addHR { get; set; }
        public Nullable<bool> TrackAccProgress { get; set; }
        public Nullable<bool> updateclassfee { get; set; }
        public Nullable<bool> updateHRpay { get; set; }
        public Nullable<bool> updateAccountant { get; set; }
        public Nullable<bool> Marks { get; set; }
        public Nullable<bool> Attendance { get; set; }
        public Nullable<bool> UpdateTeacherPay { get; set; }
        public Nullable<bool> UpdateTeacher { get; set; }
    
        public virtual roledata roledata { get; set; }
    }
}
