//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Final_Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class studfee
    {
        public int Fee_ID { get; set; }
        public Nullable<int> FeeMs_ID { get; set; }
        public Nullable<int> FeeStud_ID { get; set; }
        public Nullable<System.DateTime> Fee_date { get; set; }
        public Nullable<double> Fee_amount { get; set; }
        public Nullable<bool> Fee_status { get; set; }
    
        public virtual m m { get; set; }
        public virtual studfuctional studfuctional { get; set; }
    }
}
