//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Final_Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class subject
    {
        public subject()
        {
            this.attendanceps = new HashSet<attendancep>();
            this.marksps = new HashSet<marksp>();
            this.tchrfsubjects = new HashSet<tchrfsubject>();
        }
    
        public int Subj_ID { get; set; }
        public string Subj_name { get; set; }
        public int Cls_id { get; set; }
    
        public virtual @class @class { get; set; }
        public virtual ICollection<attendancep> attendanceps { get; set; }
        public virtual ICollection<marksp> marksps { get; set; }
        public virtual ICollection<tchrfsubject> tchrfsubjects { get; set; }
    }
}
