//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Final_Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tchrfsubject
    {
        public int TS_PKey { get; set; }
        public Nullable<int> Tchrr_ID { get; set; }
        public Nullable<int> Subjj_ID { get; set; }
    
        public virtual subject subject { get; set; }
        public virtual tchrfunctional tchrfunctional { get; set; }
    }
}
