//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.ComponentModel.DataAnnotations;
namespace Final_Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tchrfunctional
    {
        public tchrfunctional()
        {
            this.attendanceps = new HashSet<attendancep>();
            this.marksps = new HashSet<marksp>();
            this.tchrfsubjects = new HashSet<tchrfsubject>();
        }
    
        public int TchrF_ID { get; set; }
        public int TchrF_MSID { get; set; }
        public string TchrF_FName { get; set; }
        public string TchrF_LName { get; set; }
        public Nullable<System.DateTime> TchrF_DOB { get; set; }

        [DataType(DataType.PhoneNumber)]
        [RegularExpression(@"^\(?([0-9]{5})\)?[-. ]?([0-9]{7})?[-. ]?([0-9]{1})$", ErrorMessage = "Not a valid Cnic number")]
        public string TchrF_CNIC { get; set; }

        [DataType(DataType.PhoneNumber)]
        [RegularExpression(@"^\(?([0-9]{4})\)?[-. ]?([0-9]{7})$", ErrorMessage = "Not a valid phone number")]
        public string TchrF_Phone { get; set; }
        public string TchrF_Address { get; set; }
        public byte[] TchrF_Pic { get; set; }
        public string TchrF_Email { get; set; }
        public string TchrF_Gender { get; set; }
        public string TchrF_Qualif { get; set; }
        public string Tchr_GuardName { get; set; }
        public string TchrF_RollID { get; set; }
        public string TchrF_password { get; set; }
    
        public virtual m m { get; set; }
        public virtual ICollection<attendancep> attendanceps { get; set; }
        public virtual ICollection<marksp> marksps { get; set; }
        public virtual ICollection<tchrfsubject> tchrfsubjects { get; set; }
    }
}
