//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Final_Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tchrfunctional
    {
        public int TchrF_ID { get; set; }
        public int TchrF_MSID { get; set; }
        public string TchrF_FName { get; set; }
        public string TchrF_LName { get; set; }
        public Nullable<System.DateTime> TchrF_DOB { get; set; }
        public string TchrF_CNIC { get; set; }
        public string TchrF_Phone { get; set; }
        public string TchrF_Address { get; set; }
        public byte[] TchrF_Pic { get; set; }
        public string TchrF_Email { get; set; }
        public string TchrF_Gender { get; set; }
        public string TchrF_Qualif { get; set; }
        public string Tchr_GuardName { get; set; }
        public string TchrF_RollID { get; set; }
        public string TchrF_password { get; set; }
    
        public virtual m m { get; set; }
    }
}
