//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Final_Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class theme
    {
        public int ThemeID { get; set; }
        public Nullable<int> MS_primekeyid { get; set; }
        public string theme1 { get; set; }
    
        public virtual m m { get; set; }
    }
}
